steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/detection-tva', '.']

options:
  machineType: 'E2_HIGHCPU_32'

images:
  - 'gcr.io/$PROJECT_ID/detection-tva'